20222 , 25150 ko_KR iktk
kiwiyou/boj-user-translation pull request #167
Opened 2024-03-22 13:18 UTC by username230411

2024-03-23 12:35 UTC, kiwiyou requested changes
번역 감사합니다! 의견을 반영해 주세요.

2024-03-23 12:35 UTC, kiwiyou commented on src/22411/ko_KR-iktk.html
> +			<li>$1\leq N\leq10^5$</li>
\leq 뒤에 공백을 넣어 주세요.

2024-03-23 12:35 UTC, kiwiyou commented on src/25150/ko_KR-iktk.html
> +		<p>경기 결과가 주어지는 순서는 순서는 팀 번호의 사전 순입니다. 즉, $i$번 팀과 $j$번 팀의 경기를 $(i,j)$라 하면, (1,2), (1,3), ..., (1,N), (2,3), (2,4)
수식을 적용해 주세요.

2024-03-24 04:23 UTC, iktk1 commented
> 번역 감사합니다! 의견을 반영해 주세요.

써주신 대로 반영하였습니다!

2024-03-24 04:28 UTC, iktk1 commented
> > 번역 감사합니다! 의견을 반영해 주세요.
> 
> 써주신 대로 반영하였습니다!

다른 브랜치에 업로드했던 번역 2개가 포함되어버렸네요. 추가해서 검토 부탁드립니다.

2024-03-25 03:55 UTC, kiwiyou approved these changes

2024-03-25 03:55 UTC, merged