Add 16445, 5102, 9848, 17912, 8719 ez_code
kiwiyou/boj-user-translation pull request #28
Opened 2023-03-27 13:57 UTC by w8385

- [x] Did you stage index file?
- [x] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [x] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?

2023-03-27 13:58 UTC, w8385 commented
# 16445
![image](https://user-images.githubusercontent.com/52066828/227961129-0b6c10fb-febd-40db-8453-c45e32e32d72.png)

2023-03-27 14:20 UTC, w8385 commented
# 5102
![image](https://user-images.githubusercontent.com/52066828/227967803-45021bfa-f72e-4a20-881d-2e0c3b9a7a2f.png)

2023-03-27 14:51 UTC, w8385 commented
# 17912
문제 및 임력 문단에 Latex를 추가했습니다.
    
![image](https://user-images.githubusercontent.com/52066828/227976873-7f1d9ff9-9854-44a8-bbb1-7bb5a77c5eff.png)

2023-03-28 02:15 UTC, kiwiyou requested changes
번역 감사합니다! 수정사항을 반영해 주세요.

2023-03-28 02:15 UTC, kiwiyou commented on src/16445/ko_KR-ez_code.html
> +        <p>첫 줄에 시뮬레이션하는 게임의 수 $N$ ($1 \le N \le 10$<sup>$4$</sup>)이 주어집니다. 다음 N개의 줄에는 각각 차가 있는 문의 번호를 나타내는 1, 2, 3 중 하나의
변수 N에 mathjax를 적용해 주세요. 수식 안에 태그를 넣지 말아주세요.

2023-03-28 02:15 UTC, kiwiyou commented on src/17912/ko_KR-ez_code.html
> +        <p> 발사 허가가 유효한 날의 수를 나타내는 하나의 정수 $n (1 \le n \le 100000)$이 첫 번째 줄에 입력됩니다. 둘째 줄에 0부터 10<sup>9</sup> 범위의 $n$개의 정수가
자릿수 구분 기호 `\,`를 넣어 주세요. 수에 LaTeX와 HTML 형식 수식 중 하나만 선택해 적용해 주세요.

2023-03-28 02:15 UTC, kiwiyou commented on src/8719/ko_KR-ez_code.html
LaTeX 혹은 HTML 형식 수식 (em 등) 중 하나만 선택하여 적용해 주세요.

2023-03-28 02:15 UTC, kiwiyou commented on src/16445/ko_KR-ez_code.html
LaTeX를 보여주기 위해 mathjax를 삽입하지 말아주세요.

2023-03-29 07:23 UTC, w8385 commented on src/16445/ko_KR-ez_code.html
> +        <p>첫 줄에 시뮬레이션하는 게임의 수 $N$ ($1 \le N \le 10$<sup>$4$</sup>)이 주어집니다. 다음 N개의 줄에는 각각 차가 있는 문의 번호를 나타내는 1, 2, 3 중 하나의
ef2191f 수정했습니다!

2023-03-29 07:23 UTC, w8385 commented on src/16445/ko_KR-ez_code.html
ef2191f 수정했습니다!

2023-03-29 07:25 UTC, w8385 commented on src/16445/ko_KR-ez_code.html
> +        <p>첫 줄에 시뮬레이션하는 게임의 수 $N$ ($1 \le N \le 10$<sup>$4$</sup>)이 주어집니다. 다음 N개의 줄에는 각각 차가 있는 문의 번호를 나타내는 1, 2, 3 중 하나의
![image](https://user-images.githubusercontent.com/52066828/228457832-6e41cb1a-93cb-45e7-aabd-d41b94a2f098.png)

2023-03-29 07:32 UTC, w8385 commented on src/17912/ko_KR-ez_code.html
> +        <p> 발사 허가가 유효한 날의 수를 나타내는 하나의 정수 $n (1 \le n \le 100000)$이 첫 번째 줄에 입력됩니다. 둘째 줄에 0부터 10<sup>9</sup> 범위의 $n$개의 정수가
59959c0 수정했습니다!
포매팅에서 윗첨자 "^"를 금지하는 구문을 LaTeX 내부에서도 금하는 것으로 착각해서 이런 끔찍한 형식이 나왔네요..

2023-03-29 07:36 UTC, w8385 commented on src/8719/ko_KR-ez_code.html
80f6ac3 수정했습니다!

LaTeX 형식으로 통일했습니다.

2023-03-29 08:17 UTC, kiwiyou approved these changes
감사합니다!

2023-03-29 08:17 UTC, merged