Add 9310 ez_code
kiwiyou/boj-user-translation pull request #38
Opened 2023-03-31 11:29 UTC by w8385

- [ ] Did you stage index file?
- [ ] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [ ] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?

2023-03-31 11:29 UTC, w8385 commented
# 9310
![image](https://user-images.githubusercontent.com/52066828/229108647-f5648790-7a76-4aa4-a6a5-866b1dc98e64.png)

2023-03-31 13:52 UTC, w8385 commented
# 11759
![image](https://user-images.githubusercontent.com/52066828/229138968-51e33582-f88d-40d4-9f52-853df5b45708.png)

2023-03-31 14:06 UTC, w8385 commented
# 6437
![image](https://user-images.githubusercontent.com/52066828/229142956-cb9cd06a-3765-494b-9fbf-b67a1d5641b8.png)

2023-03-31 22:36 UTC, kiwiyou requested changes
번역 감사합니다! 수정사항을 반영해 주세요.

2023-03-31 22:36 UTC, kiwiyou commented on src/9298/ko_KR-ez_code.html
> +            두 소수 $X$, $Y$ $(-1000.0 \le X, Y \le 1000.0)$가 입력됩니다. 개미는 넓이가 없는 점으로 가정합니다.</p>
자리 구분자를 넣어 주세요.

2023-04-01 15:33 UTC, w8385 commented on src/9298/ko_KR-ez_code.html
> +            두 소수 $X$, $Y$ $(-1000.0 \le X, Y \le 1000.0)$가 입력됩니다. 개미는 넓이가 없는 점으로 가정합니다.</p>
[455bef0](https://github.com/kiwiyou/boj-user-translation/pull/38/commits/455bef038ab0d3f2800b598893512aa4bb9e6185) 추가했습니다!

2023-04-01 16:12 UTC, closed without merging