Add 9945, 5163 ez_code
kiwiyou/boj-user-translation pull request #45
Opened 2023-04-08 21:41 UTC by w8385

- [ ] Did you stage index file?
- [ ] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [ ] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?

2023-04-08 21:42 UTC, w8385 commented
# 9945
![image](https://user-images.githubusercontent.com/52066828/230743691-26d2bf8f-1c04-4c48-9ffb-90d84022f68a.png)

2023-04-08 21:42 UTC, w8385 commented
# 5163
![image](https://user-images.githubusercontent.com/52066828/230743699-c2791923-d6da-4bb9-9f6c-62119347f0ac.png)

2023-04-08 21:59 UTC, w8385 commented
# 10230
![image](https://user-images.githubusercontent.com/52066828/230744297-b1768c2d-1ff0-4922-a367-8d43efbaa3b2.png)

2023-04-08 23:01 UTC, w8385 commented
# 21105
![image](https://user-images.githubusercontent.com/52066828/230745981-bef2cdbe-f576-4331-8e3f-8628132cae34.png)

2023-04-08 23:15 UTC, w8385 commented
# 21614
![image](https://user-images.githubusercontent.com/52066828/230746320-fdcbb0f3-a3b3-494b-8ca8-5aa95cd4df75.png)

2023-04-08 23:29 UTC, w8385 commented
# 21420
![image](https://user-images.githubusercontent.com/52066828/230746740-53c82300-2c69-44a4-99f4-190ad31b84d4.png)

2023-04-12 12:42 UTC, w8385 commented
# 13871
![image](https://user-images.githubusercontent.com/52066828/231460674-2e247784-9f7f-4cdb-9adb-8de24e2da759.png)

2023-04-12 12:57 UTC, w8385 commented
# 21339
![image](https://user-images.githubusercontent.com/52066828/231464428-0f593dac-ac0f-41b2-9312-acf5d873418a.png)

2023-04-12 17:31 UTC, w8385 commented
# 11295
![image](https://user-images.githubusercontent.com/52066828/231537644-9518658a-babe-416c-ad72-d308b6d2ad38.png)

2023-04-13 08:21 UTC, kiwiyou requested changes
번역 감사합니다! 수정사항을 반영해 주세요.

2023-04-13 08:21 UTC, kiwiyou commented on src/10230/ko_KR-ez_code.html
> +        <p><a href="https://upload.acmicpc.net/39ff6bb2-db69-4352-a567-da480ee15e5e/">field1.txt</a> 위에 묘사한 (6x10 크기의)
`x` → `&times;`로 바꿔주세요

2023-04-13 14:20 UTC, w8385 commented on src/10230/ko_KR-ez_code.html
> +        <p><a href="https://upload.acmicpc.net/39ff6bb2-db69-4352-a567-da480ee15e5e/">field1.txt</a> 위에 묘사한 (6x10 크기의)
[677f998](https://github.com/kiwiyou/boj-user-translation/pull/45/commits/677f998c7340775e9be4be520102d93378b65ae0)
넵 수정했습니다!

2023-04-13 14:22 UTC, w8385 commented
index 파일이 충돌나는데 브랜치를 다시 생성해야할까요?

2023-04-13 15:37 UTC, kiwiyou commented
충돌은 제가 수정할 수 있습니다.

2023-04-13 15:39 UTC, merged