Add 22150, 23663, 21679 ez_code
kiwiyou/boj-user-translation pull request #49
Opened 2023-04-15 17:20 UTC by w8385

- [ ] Did you stage index file?
- [ ] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [ ] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?

2023-04-15 17:20 UTC, w8385 commented
# 22150
![image](https://user-images.githubusercontent.com/52066828/232242318-e6e75884-eb2f-4a11-bb9d-c8df974d573c.png)

2023-04-15 17:21 UTC, w8385 commented
# 23663
![image](https://user-images.githubusercontent.com/52066828/232242337-cddaf92e-2f56-4dd9-ac43-106783291784.png)

2023-04-15 17:21 UTC, w8385 commented
# 21679
![image](https://user-images.githubusercontent.com/52066828/232242356-e8aa168e-869a-4910-b517-5e7f0d3b006d.png)

2023-04-16 01:01 UTC, kiwiyou requested changes
번역 감사합니다! 수정사항을 반영해 주세요.

2023-04-16 01:01 UTC, kiwiyou commented on src/23663/ko_KR-ez_code.html
> +        <p>다음 줄에 흰 옷 노인의 흰색 돌 더미에 있는 돌의 수를 나타내는 $m$개의 정수 $b_i$ ($1 \le bi \le 10 ^ 9$)가 주어집니다.</p>
아래 첨자가 누락되었습니다.

2023-04-16 02:53 UTC, w8385 commented on src/23663/ko_KR-ez_code.html
> +        <p>다음 줄에 흰 옷 노인의 흰색 돌 더미에 있는 돌의 수를 나타내는 $m$개의 정수 $b_i$ ($1 \le bi \le 10 ^ 9$)가 주어집니다.</p>
[2923d2d](https://github.com/kiwiyou/boj-user-translation/pull/49/commits/2923d2d5d42d84de6353c6cc72249639510e3dbe) 수정했습니다!

2023-04-16 04:22 UTC, kiwiyou approved these changes

2023-04-16 04:22 UTC, merged