feat: translated problem 24860
kiwiyou/boj-user-translation pull request #56
Opened 2023-06-04 03:35 UTC by DoubleDeltas

- [v] Did you stage index file?
- [v] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [v] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?

24860번 (Counting Antibodies) 번역했습니다. 질문 게시판의 ez_code님 번역을 참조했습니다!

2023-06-05 01:52 UTC, kiwiyou requested changes
번역 감사합니다! 수정사항을 반영해 주세요.

2023-06-05 01:52 UTC, kiwiyou commented on src/24860/ko_KR-DoubleDeltas.html
> +		<p>첫번째 줄에는 각각 $\kappa$-경쇄의 $V$ 가변부와 $J$ 가변부의 유전자 조각 변형 수를 나타내는 두 정수 $V_\kappa$, $J_\kappa$가 주어집니다. ($1 \leq V\kappa, J\kappa \leq 1500$)</p>
수식에 `_`가 누락되었습니다.

2023-06-06 11:42 UTC, DoubleDeltas commented on src/24860/ko_KR-DoubleDeltas.html
> +		<p>첫번째 줄에는 각각 $\kappa$-경쇄의 $V$ 가변부와 $J$ 가변부의 유전자 조각 변형 수를 나타내는 두 정수 $V_\kappa$, $J_\kappa$가 주어집니다. ($1 \leq V\kappa, J\kappa \leq 1500$)</p>
검수 감사합니다! 수정했습니다!

2023-06-07 01:45 UTC, DoubleDeltas commented
수정했습니다!

2023-06-07 09:07 UTC, kiwiyou approved these changes

2023-06-07 09:08 UTC, merged