22381, 22389, 22396, 22656, 24074, 22518
kiwiyou/boj-user-translation pull request #93
Opened 2023-09-01 10:21 UTC by Bubbler-4

- [x] Did you stage index file?
- [x] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [x] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?

2023-09-01 13:46 UTC, kiwiyou requested changes
번역 감사합니다! 코멘트를 확인해 주세요.

2023-09-01 13:46 UTC, kiwiyou commented on src/22389/ko_KR-bubbler.html
> +			이것을 다음과 같이 일반화할 수 있다. 수열 <i>A<sub>1</sub>, ..., A<sub>n</sub></i>가 주어질 때,
`...` 대신 `&hellip;`을 써 주세요.

2023-09-01 13:46 UTC, kiwiyou commented on src/22389/ko_KR-bubbler.html
> +			수열 <i>A<sub>1</sub>, ..., A<sub>n</sub></i>과 양의 정수 <i>l, r</i>이 주어진다.
`...` 대신 `&hellip;`을 써 주세요.

2023-09-03 22:47 UTC, Bubbler-4 commented on src/22389/ko_KR-bubbler.html
> +			이것을 다음과 같이 일반화할 수 있다. 수열 <i>A<sub>1</sub>, ..., A<sub>n</sub></i>가 주어질 때,
수정했습니다.

2023-09-03 22:47 UTC, Bubbler-4 commented on src/22389/ko_KR-bubbler.html
> +			수열 <i>A<sub>1</sub>, ..., A<sub>n</sub></i>과 양의 정수 <i>l, r</i>이 주어진다.
수정했습니다.

2023-09-04 11:10 UTC, kiwiyou approved these changes

2023-09-04 11:10 UTC, merged