폴란드어 브론즈 13문제
kiwiyou/boj-user-translation pull request #94
Opened 2023-09-04 09:47 UTC by Bubbler-4

- [x] Did you stage index file?
- [x] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [x] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?

2023-09-04 11:59 UTC, kiwiyou requested changes
번역 감사합니다! 코멘트를 확인해 주세요.

2023-09-04 11:59 UTC, kiwiyou commented on src/8678/ko_KR-bubbler.html
> +			<em>b</em>&nbsp;(1 &le; <em>a</em>, <em>b</em> &le; 10<sup>9</sup>), oznaczające liczby z treści zadania.
번역이 누락된 것 같습니다.

2023-09-04 22:33 UTC, Bubbler-4 commented on src/8678/ko_KR-bubbler.html
> +			<em>b</em>&nbsp;(1 &le; <em>a</em>, <em>b</em> &le; 10<sup>9</sup>), oznaczające liczby z treści zadania.
수정했습니다.

2023-09-05 06:05 UTC, kiwiyou approved these changes

2023-09-05 06:06 UTC, merged